spring:
  datasource:
    url: jdbc:mysql://localhost:3306/managefresher
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: vinh
    password: 534473

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: apartment.management9@gmail.com
    password: vnbimwneyawoabnf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    from: apartment.management9@gmail.com



jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    valid-duration: 3600 # 3600se
    refreshable-duration: 36000 # 36000se

open:
  api:
    title: API document
    version: v1.0.0
    description: API service
    serverURL: http://localhost:8080
    serverName: server test

# -----------------------
# Email
# -----------------------
